### ISSUE TITLE
Fix dependencies for HRRR

### ISSUE THREAD

**Issue by ewquon** [NREL/SSRS#8]
SSRS Simulator cannot be initialized with `from .hrrr import HRRR` lines in code. The error may be reproduced with the following single line:
```python
from ssrs.hrrr.hrrr import HRRR
```
which results in
```
RuntimeError: Cannot find the ecCodes library
```
Diving deeper, this can actually be traced back to:
```python
import gribapi
```
which is called by the eccodes library.

**Comment by ewquon** [comment]
Working off of `alt_study` branch, which has `dev` merged into it.

**Comment by rthedin** [comment]
Using the `alt_study` branch, I'm starting with a new environment from scratch on Eagle and following the `readme` file instructions. I had to manually install additional packages needed by Herbie that do not get installed by default given Herbie dependencies. The packages are `soupsieve` (which in turn needs `bs4`) and `cartopy`.

**Comment by ewquon** [comment]
Thanks, Regis. I have an updated environment.yaml, which I'll commit with my PR to add a regression test. 
https://github.com/ewquon/SSRS/blob/93d7cc3448c0e5f1f6f05484e6c49d45ac1c359f/environment.yml

**Comment by rimplesandhu** [comment]
Did not see this in your push from yesterday. environment.yml is still the old one. @ewquon

**Comment by ewquon** [comment]
@rimplesandhu I had updated the `environment.yaml` as part of another code branch I've been developing. If you need it urgently, I can cherry pick that commit and create a new PR in the interim.

**Comment by rimplesandhu** [comment]
That's fine. I got it working on Eagle but had to install many packages manually due to Herbie dependencies.

**Comment by ewquon** [comment]
Closing this unless others still have issues.
